version: '3'
services:
  # Node.js application service
  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb+srv://preciousaffiah205:para2saha@cluster0.ojepall.mongodb.net/?retryWrites=true&w=majority"

  mongo:
    image: mongo
    ports:
      - "27017:27017"